# Generated by Django 4.1 on 2022-09-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Account_Number', models.BigIntegerField()),
                ('IFSC_code', models.CharField(max_length=50)),
                ('Branch', models.CharField(choices=[('Poonamalle', 'Poonamalle'), ('Sholinganallur', 'Sholinganallur'), ('Avadi', 'Avadi'), ('Nellore', 'Nellore'), ('kadapa', 'kadapa')], max_length=100)),
                ('Mobile_NO', models.BigIntegerField()),
                ('Email_id', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
            ],
        ),
    ]
