# Generated by Django 4.1 on 2022-09-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UIapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
