# Generated by Django 4.1 on 2022-09-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UIapp', '0002_alter_bank_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_customer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
